#!/bin/sh
banner()
{
  echo "+------------------------------------------+"
  printf "| %-40s |\n" "`date`"
  printf "| %-40s |\n" "`echo $awsinstace`"
  echo "|                                          |"
  printf "|`tput bold` %-40s `tput sgr0`|\n" "$@"
  echo "+------------------------------------------+"
}


checkVariables()
{
  echo "Checking input arguments"
  if [ -z "$awsinstance" ];
  then
        echo "AWS Instance DNS is NULL" 
        freturn=1
  fi
}

CheckUsage()
{
  echo "Usage for startCLI"
  echo "./startCLI <AWS DNS Instance>" 
  echo "AWS DNS Instance: The instance running on AWS, e.g: ec2-3-14-129-11.us-east-2.compute.amazonaws.com"
}

connectInstance()
{

#  sshuser=`whoami`
  sshuser="ec2-user"
  ssh -i "ec-thiago-teste.pem"  $sshuser@$awsinstance
  echo 0
}

unset awsinstance
freturn=0
awsinstance=$1
echo "Starting the AWS CLI custom $awsinstance" 
banner
checkVariables
if [ $freturn -eq "1" ]; then
 CheckUsage
 exit 
fi

connectInstance

